// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rghrgrpultdqjdxrcvzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnaHJncnB1bHRkcWpkeHJjdnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNjU0MDUsImV4cCI6MjA1Mzc0MTQwNX0.aUVa5XcWZuYW6UxKGbpVTtps1hwzf35gix6SUhk_BlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);